const housekeepingStaffImages = [
  "https://randomuser.me/api/portraits/thumb/women/1.jpg",
  "https://randomuser.me/api/portraits/thumb/women/2.jpg",
  "https://randomuser.me/api/portraits/thumb/women/3.jpg",
  "https://randomuser.me/api/portraits/thumb/women/4.jpg",
  "https://randomuser.me/api/portraits/thumb/women/5.jpg",
  "https://randomuser.me/api/portraits/thumb/women/6.jpg",
  "https://randomuser.me/api/portraits/thumb/women/7.jpg",
  "https://randomuser.me/api/portraits/thumb/women/8.jpg",
  "https://randomuser.me/api/portraits/thumb/women/9.jpg",
  "https://randomuser.me/api/portraits/thumb/women/10.jpg",
  "https://randomuser.me/api/portraits/thumb/women/11.jpg",
  "https://randomuser.me/api/portraits/thumb/women/12.jpg",
  "https://randomuser.me/api/portraits/thumb/women/13.jpg",
  "https://randomuser.me/api/portraits/thumb/women/14.jpg",
  "https://randomuser.me/api/portraits/thumb/women/15.jpg",
  "https://randomuser.me/api/portraits/thumb/women/16.jpg",
  "https://randomuser.me/api/portraits/thumb/women/17.jpg",
  "https://randomuser.me/api/portraits/thumb/women/18.jpg",
  "https://randomuser.me/api/portraits/thumb/women/19.jpg",
  "https://randomuser.me/api/portraits/thumb/women/20.jpg",
  "https://randomuser.me/api/portraits/thumb/women/21.jpg",
  "https://randomuser.me/api/portraits/thumb/women/22.jpg",
  "https://randomuser.me/api/portraits/thumb/women/23.jpg",
  "https://randomuser.me/api/portraits/thumb/women/24.jpg",
  "https://randomuser.me/api/portraits/thumb/women/25.jpg",
  "https://randomuser.me/api/portraits/thumb/women/26.jpg",
  "https://randomuser.me/api/portraits/thumb/women/27.jpg",
  "https://randomuser.me/api/portraits/thumb/women/28.jpg",
  "https://randomuser.me/api/portraits/thumb/women/29.jpg",
  "https://randomuser.me/api/portraits/thumb/women/30.jpg"
];

export default housekeepingStaffImages;
